version: '3.8'
services:
  fastapi:
    build: ./back
    ports:
      - "8000:8000"
    volumes:
      - ./back:/app
  nextjs:
    build: ./front
    ports:
      - "3000:3000"
    volumes:
      - ./front:/app
      - /app/node_modules

